server:
  port: 8090

spring:
  application:
    name: strangler-apigw
  cloud:
    gateway:
      routes:
      - id: modern_apis
        order: 0
        uri: http://localhost:8100
        predicates:
        - Path=/legacy/customerservice/**
        filters:
        - RewritePath=/legacy/(?<segment>.*), /api/modern/$\{segment}
      - id: legacy_apis
        order: 10000
        uri: http://localhost:8080
        predicates:
        - Path=/legacy/**
        filters:
        - RewritePath=/legacy/(?<segment>.*), /terasoluna-tourreservation-web/api/facade/$\{segment}
