server:
  port: 8110

spring:
  application:
    name: strangler-tourreservation-tourinfo
  datasource:
    name: POSTGRESQL
    url: jdbc:postgresql://localhost/tourreserve
    username: postgres
    password: P0stgres

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  